Repository ERICA-gamsung/android, pull requests merged in 2024-05, with the labels that each got.

#68 Feature/#52 , #56 뒤로가기 필요한 페이지에 GsTopAppBar 로 뒤로가기 가능한 탑바로 변경 & Navigation Stack 핸들링 하는 코드 삽입
  app/src/main/java/com/erica/gamsung/menu/presentation/InputMenuScreen.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostStatusScreen.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PreviewPost.kt
  app/src/main/java/com/erica/gamsung/post/presentation/SelectPostScreen.kt
  app/src/main/java/com/erica/gamsung/store/presentation/InputStoreScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/CalendarScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/UploadTimeConfirmScreen.kt
Labels: enhancement

#70 Feature/#69 날짜 선택 페이지 추가 기능 구현 & 버그 fix
  app/src/main/java/com/erica/gamsung/core/presentation/MainActivity.kt
  app/src/main/java/com/erica/gamsung/core/presentation/theme/Color.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostStatusScreen.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PreviewPost.kt
  app/src/main/java/com/erica/gamsung/post/presentation/SelectPostScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/CalendarScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/CalendarView.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleListScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleViewModel.kt
Labels: bug, enhancement

#74 Feature/#72, #73 메인 페이지 디자인과 기능을 구현한다
  app/src/main/java/com/erica/gamsung/core/presentation/MainActivity.kt
  app/src/main/java/com/erica/gamsung/core/presentation/MainScreen.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostStatusScreen.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostViewModel.kt
Labels: enhancement

#78 Feature/#77 소셜로그인 이후 앱 복귀 시 스플래시 다시 뜨던 버그 수정
  app/src/main/AndroidManifest.xml
Labels: bug, enhancement

#80 Feature/#79 가게 및 메뉴 입력 화면에서 뒤로 가기 시 설정 화면으로 이동하는 버그를 수정한다
  app/src/main/java/com/erica/gamsung/core/presentation/MainActivity.kt
  app/src/main/java/com/erica/gamsung/menu/presentation/InputMenuScreen.kt
  app/src/main/java/com/erica/gamsung/menu/presentation/MenuViewModel.kt
  app/src/main/java/com/erica/gamsung/store/presentation/InputStoreScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleScreen.kt
  app/src/test/java/com/erica/gamsung/menu/presentation/InputMenuViewModelTest.kt
Labels: bug, enhancement

#82 Feature/#41, #81 네비게이션 관련 버그 수정
  app/src/main/java/com/erica/gamsung/core/presentation/MainActivity.kt
  app/src/main/java/com/erica/gamsung/login/presentation/LoginViewModel.kt
  app/src/main/java/com/erica/gamsung/menu/presentation/InputMenuScreen.kt
  app/src/main/java/com/erica/gamsung/menu/presentation/MenuViewModel.kt
Labels: bug, enhancement

#84 Fix: Main 버튼 디자인 수정 & 발행 현황 확인하기 페이지 state 아이콘으로 변경
  app/src/main/java/com/erica/gamsung/core/presentation/MainActivity.kt
  app/src/main/java/com/erica/gamsung/core/presentation/MainScreen.kt
  app/src/main/java/com/erica/gamsung/core/presentation/component/GsButton.kt
  app/src/main/java/com/erica/gamsung/core/presentation/theme/Color.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostStatusScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleListScreen.kt
Labels: enhancement

#86 Fix: Diaglog에서 선택한 시간 외부 박스에 반영
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleScreen.kt
Labels: bug

#87 Feature/#22 마이페이지 기능을 구현한다
  app/src/main/java/com/erica/gamsung/login/data/remote/LoginApi.kt
  app/src/main/java/com/erica/gamsung/login/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/erica/gamsung/login/domain/LoginRepository.kt
  app/src/main/java/com/erica/gamsung/login/presentation/LoginViewModel.kt
  app/src/main/java/com/erica/gamsung/setting/presentation/SettingScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/data/remote/ScheduleApi.kt
  app/src/main/java/com/erica/gamsung/uploadTime/data/repository/ScheduleRepository.kt
Labels: enhancement
