Repository ERICA-gamsung/android, pull requests merged in 2024-06, with the labels that each got.

#89 Feature #88 회원탈퇴 다이얼로그 추가
  app/src/main/java/com/erica/gamsung/setting/presentation/SettingScreen.kt
Labels: enhancement

#91 Fix: SelectPostScreen PreviewPost 이동에서 선택했던 이미지 view에서 보여지는 것 수정
  app/src/main/java/com/erica/gamsung/post/presentation/SelectPostScreen.kt
Labels: bug

#93 Feature #92 글 확정 API 호출 후에 인스타그램에 업로드 되지 않던 버그를 수정한다
  app/src/main/java/com/erica/gamsung/post/presentation/PostViewModel.kt
Labels: bug, enhancement

#95 Feature/#94 PostStatus 페이지 디자인 변경 및 타 페이지 디자인 변경사항 적용
  app/src/main/java/com/erica/gamsung/core/presentation/theme/Color.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostStatusScreen.kt
  app/src/main/java/com/erica/gamsung/post/presentation/SelectPostScreen.kt
  app/src/main/java/com/erica/gamsung/uploadTime/presentation/ScheduleListScreen.kt
Labels: enhancement

#97 Feature/#96 바뀐 발행현황 API에 맞춰 요청한다
  app/src/main/java/com/erica/gamsung/login/data/remote/LoginApi.kt
  app/src/main/java/com/erica/gamsung/login/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/erica/gamsung/login/domain/LoginRepository.kt
  app/src/main/java/com/erica/gamsung/menu/data/repository/FakeMenuRepositoryImpl.kt
  app/src/main/java/com/erica/gamsung/menu/data/repository/MenuRepositoryImpl.kt
  app/src/main/java/com/erica/gamsung/menu/domain/MenuRepository.kt
  app/src/main/java/com/erica/gamsung/menu/presentation/MenuViewModel.kt
  app/src/main/java/com/erica/gamsung/post/data/remote/PostApi.kt
  app/src/main/java/com/erica/gamsung/post/presentation/PostViewModel.kt
Labels: enhancement

#99 Feature #98 변경된 가게 API에 맞게 수정
  app/src/main/java/com/erica/gamsung/store/data/repository/StoreRepositoryImpl.kt
  app/src/main/java/com/erica/gamsung/store/domain/StoreRepository.kt
  app/src/main/java/com/erica/gamsung/store/presentation/StoreViewModel.kt
Labels: enhancement
